# Generated by Django 5.1.6 on 2025-03-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_notes_created_at_notes_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='description',
        ),
        migrations.AddField(
            model_name='notes',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
